### ISSUE TITLE
Installation errors with requirements.txt 

### ISSUE THREAD

**Issue by kidukkang** [alexatartaglini/same-different-eval#1]
First, I have to say it's such a cool research you did! I enjoyed reading your paper very much :)

when installing requirements with
`pip install -r requirements.txt`

I get the error
`ERROR: Could not find a version that satisfies the requirement clip==1.0 (from versions: 0.0.1, 0.1.0, 0.2.0)
ERROR: No matching distribution found for clip==1.0`

I believe pip install clip refers to https://pypi.org/project/clip/
The line should be changed to refer `git+https://github.com/openai/CLIP.git`.

Also, requirements.txt has 2 different viersion of Pillow,
and I get conflicting dependencies between torchvision and torch,

````
ERROR: Cannot install -r requirements.txt (line 7) and torch==2.2.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested torch==2.2.0
    torchvision 0.15.1 depends on torch==2.0.0
````

**Comment by alexatartaglini** [comment]
Hey, thank you so much for reading our paper and for bringing my attention to these issues! I think I corrected the requirements.txt file. Try it out and let me know if it's still broken.

**Comment by aishaahmadd** [comment]
Hi Alexa,

I was able to run `pip install -r requirements.txt` without any issues. Thank you @kdkangg for flagging it!
